### ISSUE TITLE
Readme does not mention that there are helpful slides in the repo

### ISSUE THREAD

**Issue by ltfschoen** [substrate-developer-hub/utxo-workshop#12]
It doesn't mention in the Readme that there are [slides](https://github.com/nczhu/utxo-workshop/blob/master/%5B24_4_19%5D%20Sub0_%20UTXO%20workshop.pdf) in the repo that includes additional context such as the purpose of the UXTO workshop, definitions, what the UTXO model is, examples, hints, etc

**Comment by nczhu** [comment]
Thanks! I'm overhauling this workshop which will resolve this particular issue. Closing this issue for now.
