### ISSUE TITLE
Slide 22 example does not have description

### ISSUE THREAD

**Issue by ltfschoen** [substrate-developer-hub/utxo-workshop#14]
It doesn't say what's going on in the Slide 22 example.
I can only based on looking at the pictures that Alice 
is sending half her balance to Clair, and the other half to Dave,
whilst Bob is sending half his balance to Eve.

**Comment by nczhu** [comment]
Thanks! I'm overhauling this workshop which will resolve this particular issue. Closing this issue for now.
