### ISSUE TITLE
Slide 25 does not explain how to interpret the code shown

### ISSUE THREAD

**Issue by ltfschoen** [substrate-developer-hub/utxo-workshop#15]
For this workshop to be 'self guided' I think the slide with title "UTXO is stored in UnspentOutputs" should be updated as follows:

* Show a link to the source code file where this code snippet was extracted from (i.e. https://github.com/nczhu/utxo-workshop/blob/workshop/runtime/src/utxo.rs#L79)
* Provide a link to the relevant Rustdocs for `decl_storage` that the user should refer to in order to interpret this code snippet https://crates.parity.io/srml_support_procedural/macro.decl_storage.html. Explain that `build` initialises the genesis config, and that `map H256` is the type associated with storage name `UnspendOutputs` that implements `StorageMap`, and that they should refer to the Rustdocs for more information.
* I think it would be better to show it as the following (so it includes `decl_storage`):
```
decl_storage! {
    trait Store for Module<T: Trait> as Utxo {
        UnspentOutputs build(|config: &GenesisConfig<T>| {
            config.initial_utxo
                .iter()
                .cloned()
                .map(|u| (BlakeTwo256::hash_of(&u), u))
                .collect::<Vec<_>>()
        }): map H256 => Option<TransactionOutput>;
```

**Comment by nczhu** [comment]
Thanks! I'm overhauling this workshop which will resolve this particular issue. Closing this issue for now.
