### ISSUE TITLE
Slide 26 code snippet differs from codebase but doesn't explain the difference or why they differ

### ISSUE THREAD

**Issue by ltfschoen** [substrate-developer-hub/utxo-workshop#16]
Slide 26 doesn't show the same as what's shown in the code `pubkey: H256::from_slice(&NICOLE),`, and it doesn't say what the slide shows `pubkey: H256::zero(),` instead

**Comment by nczhu** [comment]
Thanks! I'm overhauling this workshop which will resolve this particular issue. Closing this issue for now.

**Comment by nczhu** [comment]
Thanks! I'm overhauling this workshop which will resolve this particular issue. Closing this issue for now.
