### ISSUE TITLE
Slide 28-29 should show they are part of `decl_module` and the main module implementation block respectively with more circles around relevant parts of the code

### ISSUE THREAD

**Issue by ltfschoen** [substrate-developer-hub/utxo-workshop#17]
Slide 28 should show link to relevant part of Example SRML https://github.com/paritytech/substrate/blob/master/srml/example/src/lib.rs#L346, and code snippet like below with circles around relevant methods like has already been done.

It should also include a link to decl_module in the Substrate Dev Hub https://docs.substrate.dev/docs/decl_module & https://crates.parity.io/srml_support/macro.decl_module.html

```
decl_module! {
        ...

        /// Dispatch a single transaction and update UTXO set accordingly
        pub fn execute(origin, transaction: Transaction) -> Result {
                ...
                let leftover = match Self::check_transaction(&transaction)? {
                        ...
                }
                ...
                Self::update_storage(&transaction, leftover)?;
                ...
        }
        
        ...
}
```

Slide 29 should show link to relevant part of Example SRML https://github.com/paritytech/substrate/blob/master/srml/example/src/lib.rs#L464, and code snippet like below with circles around relevant methods like has already been done.

```
impl<T: Trait> Module<T> {
    pub fn check_transaction(transaction: &Transaction) -> CheckResult<'_> {
        ...
    }

    ...

    fn update_storage(transaction: &Transaction, leftover: Value) -> Result {
        ...
    }
    
    ...
}
```

**Comment by nczhu** [comment]
Thanks! I'm overhauling this workshop which will resolve this particular issue. Closing this issue for now.
