### ISSUE TITLE
Slide 36 add links to documentation that describes on_finalize

### ISSUE THREAD

**Issue by ltfschoen** [substrate-developer-hub/utxo-workshop#21]
When explaining `on_finalize`, add links to:
* Block finalization trait https://github.com/paritytech/substrate/blob/master/core/sr-primitives/src/traits.rs#L330
* Example SRML https://github.com/paritytech/substrate/blob/master/srml/example/src/lib.rs#L442

**Comment by ltfschoen** [comment]
Actually, even better would be to link to where its discussed in the Substrate Dev Hub https://docs.substrate.dev/docs/decl_module#section-on_initialise-and-on_finalise-

**Comment by nczhu** [comment]
Thanks! I'm overhauling this workshop which will resolve this particular issue. Closing this issue for now.
