### ISSUE TITLE
Slide 36 mentions `spend_dust` but it does not exist in uxto-workshop branches or anywhere in the Substrate repo

### ISSUE THREAD

**Issue by ltfschoen** [substrate-developer-hub/utxo-workshop#22]
I can only only find a `type DustRemoval = ();` in uxto-workshop

Is the reader supposed to implement something similar to what's in the Balances SRML https://github.com/paritytech/substrate/blob/master/srml/balances/src/lib.rs#L205?

**Comment by nczhu** [comment]
Thanks! I'm overhauling this workshop which will resolve this particular issue. Closing this issue for now.
