### ISSUE TITLE
Slide 41-42 add more context

### ISSUE THREAD

**Issue by ltfschoen** [substrate-developer-hub/utxo-workshop#24]
* Add link to source of the code snippet with `validate_transaction` i.e. https://github.com/nczhu/utxo-workshop/blob/workshop/runtime/src/lib.rs#L286
* Add link to `TransactionValidity` in the slides too https://crates.parity.io/sr_primitives/transaction_validity/enum.TransactionValidity.html. And the source code where it comes from https://github.com/paritytech/substrate/blob/master/core/sr-primitives/src/transaction_validity.rs#L35
* Show another slide before both of these that shows where these code snippets fit in (how it's imported, i.e.:
```
...
use runtime_primitives::{
    ...
    transaction_validity::TransactionValidity,
    ...
};

...

// Reference: https://docs.substrate.dev/docs/construct_runtime
construct_runtime!(
   ...
);

// Implement our runtime API endpoints. This is just a bunch of proxying.
impl_runtime_apis! {
    ...

    impl runtime_api::TaggedTransactionQueue<Block> for Runtime {
        fn validate_transaction(tx: <Block as BlockT>::Extrinsic) -> TransactionValidity {
            ...
        }
    }
...
}
```

**Comment by nczhu** [comment]
Thanks! I'm overhauling this workshop which will resolve this particular issue. Closing this issue for now.
