### ISSUE TITLE
Incorrect comment in utxo.rs

### ISSUE THREAD

**Issue by JoshOrndorff** [substrate-developer-hub/utxo-workshop#34]
https://github.com/substrate-developer-hub/utxo-workshop/blob/78135708fe787c1c13f5a9e16601f4b17bab53e4/runtime/src/utxo.rs#L20-L24

Line 23 is copied from the previous `type` definition

**Comment by nczhu** [comment]
Thanks! I'm overhauling this workshop which will resolve this particular issue. Closing this issue for now.
