### ISSUE TITLE
Critical front-running issue where nodes can listen to valid transaction and then claim the utxo

### ISSUE THREAD

**Issue by nczhu** [substrate-developer-hub/utxo-workshop#36]
To repro:
1. Malicious node can listen to valid trxs on the network
2. She can then change any attributes in `TransactionOutput` in the input Transaction, e.g. changing the pubkey recipient to herself, lowering the value to recipient, changing te salt, etc.
3. She then changes `total value` of new utxos to be lower, thus increasing `leftover` value. This prioritizes her new malicious trx above the original trx, thus frontrunning!

Bitcoin users sign the entire trx, whereas we're only asking users to sign the trx input. So we can adopt a similar approach and have the spender sign recipient addr...

**Not great solutions**
1. Have the user sign/submit a hash (`output` (the input utxo address), `vec<TransactionOutput>` (which contains recipient pubkeys and values) ) using the same private key that owns the utxo input. Thus we guarantee that the new UTXOs will not be tampered by whoever doesn't own at least one of the `output` keys. But this means if I run a node and one of my utxos is input, then i can still frontrun.

2. Do (1) and limit functionality for the user s.t. all input utxo need to be signed by the same private key. This means removing the proof field from Transaction inputs, which doesn't necessarily break the utxo ledger model... This is a design decision on who gets to decide/sign who the actual utxo recipients are ... the input-utxo owners, the extrinsic sender...

3. Like in Bitcoin, **save and reference the entire (prev)transaction hash rather than just the utxo hash**.    So the `ScriptSig` of each utxo input is a signed message of the entire transaction, including the output recipients. Basically: 
```
TransactionInput {
    Prev Trx hash, 
    SigScript (signed over the entire message containing output)
}
```

### Option 4 - Serialize and sign the entire trx
I think I'm going to go with the following:
1. For each trx input, user signs the entire Transaction without `script` field, basically:
```
TransactionInput {
    output
    script: INITIALLY EMPTY
} ...
TransactionOutput {
   value
   pubkey
   salt
} ...
```
2. User repopulates trx inputs to contain the corresponding scripts. i.e.: 
```
TransactionInput {
    output
    script: private key signing entire Trx including TrxOutput parameters, thus tamper-proofing them
} ...
TransactionOutput {
   value
   pubkey
   salt
} ...
```

3. In `check_transaction` we verify that each utxo-input's script is indeed signed over entire transaction and also itself && **that the key still matches the pubkey of the utxo**.

On a UX/feature level, this means all input-utxo key owners need to agree on the entire transaction & output outcome... which is fine i guess...

**Comment by nczhu** [comment]
Sub steps: 
- [ ] change `check_transaction` to verify that each utxoinput `signature` signs over the entire Transaction (ignoring the signature field) && that `signature` still matches pubkey authorized to spend utxo. 
- [ ] make tests pass

**Comment by jiayaoqijia** [comment]
I think you can sign everything in the txn including parent hash and multi outputs, then it should be ok. It also requires a good way for the serialization of multi outputs.
