### ISSUE TITLE
Fix tests so it checks for error message, not just "there is an error"

### ISSUE THREAD

**Issue by nczhu** [substrate-developer-hub/utxo-workshop#49]

**Comment by JoshOrndorff** [comment]
We should start using the `decl_error!` macro. I think it didn't exist when UTXO was first written.

**Comment by nczhu** [comment]
oh cool. will look into this

**Comment by JoshOrndorff** [comment]
Some resources about it.
https://substrate.dev/rustdocs/master/frame_support/macro.decl_error.html
https://substrate.dev/recipes/2-appetizers/3-errors.html

I'd be happy to make a PR for this after your big one is merged. (Don't want to resolve too many conflicts.)
