### ISSUE TITLE
Update to Substrate v2.0.0-alpha.5 (or later)

### ISSUE THREAD

**Issue by JoshOrndorff** [substrate-developer-hub/utxo-workshop#54]
I'd be happy to take this after the `v2` branch is merged.

**Comment by nczhu** [comment]
Cool thanks! do we have a writeup on what the key feature level/api level changes are? would amazing to have a V___ diff file in dev hub for every new breaking version.

**Comment by JoshOrndorff** [comment]
closed in #58 

Substrate repo has a [CHANGELOG](https://github.com/paritytech/substrate/blob/master/docs/CHANGELOG.md) starting at `v2.0.0-alpha.3` but not as far back as `pre-v2.0.0-3e65111` which this project was based on before #58.
