### ISSUE TITLE
Extend UTXO to be a PoW Chain

### ISSUE THREAD

**Issue by nczhu** [substrate-developer-hub/utxo-workshop#56]
Changing PoS -> PoW w/ Joshy.

**Comment by JoshOrndorff** [comment]
Some example material for how to start tackling this.
https://substrate.dev/recipes/3-entrees/basic-pow.html
https://github.com/kulupu/kulupu/tree/master/rewards
(vaguely related) https://github.com/JoshOrndorff/cle-coin

**Comment by JoshOrndorff** [comment]
This change is also related to https://github.com/substrate-developer-hub/utxo-workshop/issues/53
