### ISSUE TITLE
startercode cargo check utxo-runtime error 

### ISSUE THREAD

**Issue by motomoto-254** [substrate-developer-hub/utxo-workshop#85]
cargo check -p utxo-runtime
   Compiling utxo-runtime v2.0.0-alpha.5 (C:\Users\Mwaki\utxo-workshop\runtime)
    Checking parity-util-mem v0.6.0
error[E0308]: mismatched types
  --> C:\Users\Mwaki\.cargo\registry\src\github.com-1ecc6299db9ec823\parity-util-m\allocators.rs:76:30
   |
76 |                 if HeapValidate(heap, 0, ptr) == 0 {
   |                                          ^^^ expected enum `winapi::ctypes::cd enum `std::ffi::c_void`
   |
   = note: expected raw pointer `*const winapi::ctypes::c_void`
              found raw pointer `*const std::ffi::c_void`

error[E0308]: mismatched types
  --> C:\Users\Mwaki\.cargo\registry\src\github.com-1ecc6299db9ec823\parity-util-m\allocators.rs:80:23
   |
80 |                 HeapSize(heap, 0, ptr) as usize
   |                                   ^^^ expected enum `winapi::ctypes::c_void`,`std::ffi::c_void`
   |
   = note: expected raw pointer `*const winapi::ctypes::c_void`
              found raw pointer `*const std::ffi::c_void`

error: aborting due to 2 previous errors

For more information about this error, try `rustc --explain E0308`.
error: could not compile `parity-util-mem`

To learn more, run the command again with --verbose.
warning: build failed, waiting for other jobs to finish...
error: build failed

any help to solve the above error would be highly appreciated.

**Comment by ical10** [comment]
I've encountered the same issue. Have you been able to fix this @motomoto-254 ? I'd appreciate any pointers, thank you.

**Comment by motomoto-254** [comment]
I didn't solve the problem, i changed my approach. So i started the tutorial on the official substrate website with rust to get up n running with the rust language n substrate dev.
Link to the website: 
https://substrate.dev/docs/en/tutorials/create-your-first-substrate-chain/index

**Comment by bhavesh20-mb** [comment]
yes same problem please help,any solution ?

**Comment by motomoto-254** [comment]
Hi, sorry to disappoint. I haven't followed up, though from the website it
explains the set up of your "work station" i think i got it wrong from the
start.
They have updated the website, you could get more help from there..
https://docs.substrate.io
